require_relative 'configuration.rb'
require_relative 'price_logic_base.rb'
require_relative 'counters/array_counter.rb'
require_relative 'counters/character_counter.rb'
require_relative 'counters/html_node_counter.rb'